# Generated by Django 5.2.5 on 2025-08-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_record_options_record_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date', '-time_in']},
        ),
    ]
